package org.example.escriturarapida;

public class Palabra {

    public static String[] palabrasFaciles = {
            "Pepe",
            "Rodolfo",
            "JavaFX",
            "Mártir",
            "Hola mundo",
            "Computadora",
            "Teclado",
            "Ventana",
            "Desarrollo",
            "Algoritmo",
            "Variable",
            "Método",
            "Controlador",
            "Interfaz",
            "Software",
            "Aplicación",
            "Proyecto",
            "Tecnología",
            "Estudiante",
            "Universidad",
            "Profesor",
            "Programa",
            "Programación",
            "Computación",
            "Informática",
            "Ingeniería",
            "Electricidad",
            "Matemática",
            "Geometría",
            "Conjunto",
            "Función",
    };



    public static String[] palabrasMedias = {
            "Escritura rápida",
            "Código fuente",
            "Programación",
            "Inteligencia",
            "Desarrollo",
            "Sistema operativo",
            "Computación",
            "Tecnología",
            "Aplicación",
            "Información",
            "Configuración",
            "Comunicación",
            "Organización",
            "Estructura de datos",
            "Base de datos",
            "Interfaz gráfica",
            "Proyecto académico",
            "Sistema informático",
            "Archivo de texto",
            "Red de computadores",
            "Conexión inalámbrica",
            "Seguridad informática",
            "Diseño de software",
            "Desarrollo web",
            "Página principal",
            "Menú de opciones"
    };


    public static String[] palabrasDificiles = {
            "Programación avanzada",
            "Administración pública",
            "Configuración avanzada",
            "Implementación tecnológica",
            "Investigación científica",
            "Documentación técnica",
            "Comunicación digital",
            "Optimización computacional",
            "Arquitectura informática",
            "Funcionamiento interno",
            "Procesamiento paralelo",
            "Almacenamiento electrónico",
            "Desarrollador profesional",
            "Computación cuántica",
            "Electrónica digital",
            "Matemáticas aplicadas",
            "Estadística descriptiva",
            "Probabilidad matemática",
            "Representación gráfica",
            "Transformación digital",
            "Caracterización numérica",
            "Interpretación matemática",
            "Experimentación científica",
            "Clasificación automática",
            "Identificación biométrica",
            "Multiplicación matricial",
            "Personalización avanzada",
            "Conectividad inalámbrica",
            "Compatibilidad tecnológica",
            "Interactividad gráfica",
            "Productividad académica",
            "Accesibilidad digital",
            "Internacionalización empresarial",
            "Administración informática",
            "Desarrollo tecnológico",
            "Análisis computacional",
            "Algoritmo matemático",
            "Estructuración jerárquica",
            "Programación orientada",
            "Virtualización informática"
    };


    public static String[] palabrasImposibles = {
            "Desoxirribonucleico",
            "Esternocleidomastoideo",
            "Otorrinolaringólogo",
            "Electroencefalograma",
            "Electrocardiograma",
            "Paralelepípedo",
            "Anticonstitucionalmente",
            "Inconstitucionalidad",
            "Extraordinariamente",
            "Ovivíparo",
            "Hermafrodita",
            "Arqueopterix",
            "Inmunodeficiencia",
            "Neurotransmisor",
            "Fotosíntesis",
            "Microorganismo",
            "Metamorfosis",
            "Idiosincrasia",
            "Epistemología",
            "Ontológicamente",
            "Circunferencia",
            "Perpendicularidad",
            "Irreversibilidad",
            "Ininteligible",
            "Otorrinolaringología",
            "Electrodoméstico",
            "Termodinámica",
            "Espectrofotómetro",
            "Cromatografía",
            "Cristalización",
            "Descontextualización",
            "Incompatibilidad",
            "Extraordinario",
            "Quimiosíntesis",
            "Fotosintéticamente",
            "Hipercolesterolemia",
            "Gastroenterología",
            "Neurodegenerativo",
            "Inmunohistoquímica",
            "Electromagnetismo"
    };

}
